//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntitySpecific {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntitySpecific() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmsFeedback_EFModels.GlobalResources.EntitySpecific", typeof(EntitySpecific).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string contact_Email {
            get {
                return ResourceManager.GetString("contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email format.
        /// </summary>
        public static string contact_EmailFormatIncorrect {
            get {
                return ResourceManager.GetString("contact_EmailFormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is required.
        /// </summary>
        public static string contact_EmailRequired {
            get {
                return ResourceManager.GetString("contact_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string contact_Name {
            get {
                return ResourceManager.GetString("contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name field is required.
        /// </summary>
        public static string contact_NameRequired {
            get {
                return ResourceManager.GetString("contact_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string contact_Surname {
            get {
                return ResourceManager.GetString("contact_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Surname field is required.
        /// </summary>
        public static string contact_SurnameRequired {
            get {
                return ResourceManager.GetString("contact_SurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Day.
        /// </summary>
        public static string sd_BillingDay {
            get {
                return ResourceManager.GetString("sd_BillingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid day: must be between 1 and 25.
        /// </summary>
        public static string sd_BillingDayErrorNotInInterval {
            get {
                return ResourceManager.GetString("sd_BillingDayErrorNotInInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Currency.
        /// </summary>
        public static string sd_DefaultCurrency {
            get {
                return ResourceManager.GetString("sd_DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra credit purchased this month.
        /// </summary>
        public static string sd_ExtraAddedCreditThisMonth {
            get {
                return ResourceManager.GetString("sd_ExtraAddedCreditThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit remaining from previous months.
        /// </summary>
        public static string sd_RemainingCreditFromPreviousMonth {
            get {
                return ResourceManager.GetString("sd_RemainingCreditFromPreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining SMS (from those included).
        /// </summary>
        public static string sd_RemainingSMS {
            get {
                return ResourceManager.GetString("sd_RemainingSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending limit.
        /// </summary>
        public static string sd_SpendingLimit {
            get {
                return ResourceManager.GetString("sd_SpendingLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costs of SMS send (non included in subscription).
        /// </summary>
        public static string sd_SpentThisMonth {
            get {
                return ResourceManager.GetString("sd_SpentThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS included in subscription.
        /// </summary>
        public static string sd_SubscriptionSMS {
            get {
                return ResourceManager.GetString("sd_SubscriptionSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning limit.
        /// </summary>
        public static string sd_WarningLimit {
            get {
                return ResourceManager.GetString("sd_WarningLimit", resourceCulture);
            }
        }
    }
}
