//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmsFeedback_Take4.GlobalResources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string accountAuthenticate {
            get {
                return ResourceManager.GetString("accountAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string accountInformation {
            get {
                return ResourceManager.GetString("accountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a tag.
        /// </summary>
        public static string addATagLabel {
            get {
                return ResourceManager.GetString("addATagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string dateLabel {
            get {
                return ResourceManager.GetString("dateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send us feedback.
        /// </summary>
        public static string feedbackSendUsFeedback {
            get {
                return ResourceManager.GetString("feedbackSendUsFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add filtering tag.
        /// </summary>
        public static string filteringAddFilterTag {
            get {
                return ResourceManager.GetString("filteringAddFilterTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initiated.
        /// </summary>
        public static string fromDate {
            get {
                return ResourceManager.GetString("fromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string helpPageTitle {
            get {
                return ResourceManager.GetString("helpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conversation selected, please select one.
        /// </summary>
        public static string lblNoConversationSelected {
            get {
                return ResourceManager.GetString("lblNoConversationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more conversations.
        /// </summary>
        public static string loadMoreConversations {
            get {
                return ResourceManager.GetString("loadMoreConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string loginUnsuccessfulDetails {
            get {
                return ResourceManager.GetString("loginUnsuccessfulDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string loginUnsuccessfulSummary {
            get {
                return ResourceManager.GetString("loginUnsuccessfulSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOnButtonMessage {
            get {
                return ResourceManager.GetString("LogOnButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string logOnLogOffMsg {
            get {
                return ResourceManager.GetString("logOnLogOffMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on.
        /// </summary>
        public static string logOnLogOnMsg {
            get {
                return ResourceManager.GetString("logOnLogOnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string logOnMessage {
            get {
                return ResourceManager.GetString("logOnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LogOnModel_Password_DisplayName {
            get {
                return ResourceManager.GetString("LogOnModel_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required.
        /// </summary>
        public static string LogOnModel_Password_Required {
            get {
                return ResourceManager.GetString("LogOnModel_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string LogOnModel_RememberMe_DisplayName {
            get {
                return ResourceManager.GetString("LogOnModel_RememberMe_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LogOnModel_UserName_DisplayName {
            get {
                return ResourceManager.GetString("LogOnModel_UserName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User name field is required.
        /// </summary>
        public static string LogOnModel_UserName_Required {
            get {
                return ResourceManager.GetString("LogOnModel_UserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string logOnRegister {
            get {
                return ResourceManager.GetString("logOnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have an account.
        /// </summary>
        public static string logOnRegisterSuffixMsg {
            get {
                return ResourceManager.GetString("logOnRegisterSuffixMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user name and password..
        /// </summary>
        public static string logOnWithUserPassMsg {
            get {
                return ResourceManager.GetString("logOnWithUserPassMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add tag.
        /// </summary>
        public static string messagesAddTagPlaceHolder {
            get {
                return ResourceManager.GetString("messagesAddTagPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversations.
        /// </summary>
        public static string messagesPageTitle {
            get {
                return ResourceManager.GetString("messagesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread.
        /// </summary>
        public static string readLabel {
            get {
                return ResourceManager.GetString("readLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of incoming SMS per customer.
        /// </summary>
        public static string RepAvgNoOfIncomingSmsPerConversation {
            get {
                return ResourceManager.GetString("RepAvgNoOfIncomingSmsPerConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of incoming SMS per customer.
        /// </summary>
        public static string RepAvgNoOfIncomingSmsPerConversationToolitp {
            get {
                return ResourceManager.GetString("RepAvgNoOfIncomingSmsPerConversationToolitp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of outgoing SMS per customer.
        /// </summary>
        public static string RepAvgNoOfOutgoingSmsPerConversation {
            get {
                return ResourceManager.GetString("RepAvgNoOfOutgoingSmsPerConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of outgoing SMS per customer.
        /// </summary>
        public static string RepAvgNoOfOutgoingSmsPerConversationTooltip {
            get {
                return ResourceManager.GetString("RepAvgNoOfOutgoingSmsPerConversationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of SMS per customer.
        /// </summary>
        public static string RepAvgNoOfSmsPerClient {
            get {
                return ResourceManager.GetString("RepAvgNoOfSmsPerClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of SMS per customer.
        /// </summary>
        public static string RepAvgNoOfSmsPerClientTooltip {
            get {
                return ResourceManager.GetString("RepAvgNoOfSmsPerClientTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of SMS per day.
        /// </summary>
        public static string RepAvgNoOfSmsPerDay {
            get {
                return ResourceManager.GetString("RepAvgNoOfSmsPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of SMS per day.
        /// </summary>
        public static string RepAvgNoOfSmsPerDayTooltip {
            get {
                return ResourceManager.GetString("RepAvgNoOfSmsPerDayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of tags per conversation.
        /// </summary>
        public static string RepAvgNoOfTagsPerConversation {
            get {
                return ResourceManager.GetString("RepAvgNoOfTagsPerConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of tags per conversation.
        /// </summary>
        public static string RepAvgNoOfTagsPerConversationTooltip {
            get {
                return ResourceManager.GetString("RepAvgNoOfTagsPerConversationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average response time.
        /// </summary>
        public static string RepAvgResponseTime {
            get {
                return ResourceManager.GetString("RepAvgResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average response time.
        /// </summary>
        public static string RepAvgResponseTimeTooltip {
            get {
                return ResourceManager.GetString("RepAvgResponseTimeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string RepClients {
            get {
                return ResourceManager.GetString("RepClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers.
        /// </summary>
        public static string RepClientsUnit {
            get {
                return ResourceManager.GetString("RepClientsUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversations.
        /// </summary>
        public static string RepConversations {
            get {
                return ResourceManager.GetString("RepConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string RepDay {
            get {
                return ResourceManager.GetString("RepDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming SMS.
        /// </summary>
        public static string RepIncomingSmsChart {
            get {
                return ResourceManager.GetString("RepIncomingSmsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming &amp; Outgoing.
        /// </summary>
        public static string RepIncomingVsOutgoing {
            get {
                return ResourceManager.GetString("RepIncomingVsOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string RepMinutesUnit {
            get {
                return ResourceManager.GetString("RepMinutesUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string RepMonth {
            get {
                return ResourceManager.GetString("RepMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most used tags.
        /// </summary>
        public static string RepMostUsedTag {
            get {
                return ResourceManager.GetString("RepMostUsedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most used tags.
        /// </summary>
        public static string RepMostUsedTagsTooltip {
            get {
                return ResourceManager.GetString("RepMostUsedTagsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New customers.
        /// </summary>
        public static string RepNewClientsChart {
            get {
                return ResourceManager.GetString("RepNewClientsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New vs Returning.
        /// </summary>
        public static string RepNewVsReturning {
            get {
                return ResourceManager.GetString("RepNewVsReturning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string RepNoneDefaultValue {
            get {
                return ResourceManager.GetString("RepNoneDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of incoming SMS.
        /// </summary>
        public static string RepNoOfIncomingSms {
            get {
                return ResourceManager.GetString("RepNoOfIncomingSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of incoming SMS.
        /// </summary>
        public static string RepNoOfIncomingSmsTooltip {
            get {
                return ResourceManager.GetString("RepNoOfIncomingSmsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of new customers.
        /// </summary>
        public static string RepNoOfNewClients {
            get {
                return ResourceManager.GetString("RepNoOfNewClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of new customers.
        /// </summary>
        public static string RepNoOfNewClientsTooltip {
            get {
                return ResourceManager.GetString("RepNoOfNewClientsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of outgoing SMS.
        /// </summary>
        public static string RepNoOfOutgoingSms {
            get {
                return ResourceManager.GetString("RepNoOfOutgoingSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of outgoing SMS.
        /// </summary>
        public static string RepNoOfOutgoingSmsTooltip {
            get {
                return ResourceManager.GetString("RepNoOfOutgoingSmsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of returning customers.
        /// </summary>
        public static string RepNoOfReturningClients {
            get {
                return ResourceManager.GetString("RepNoOfReturningClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of returning customers.
        /// </summary>
        public static string RepNoOfReturningClientsTooltip {
            get {
                return ResourceManager.GetString("RepNoOfReturningClientsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string reportsPageTitle {
            get {
                return ResourceManager.GetString("reportsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing .
        /// </summary>
        public static string RepOutgoingSmsChart {
            get {
                return ResourceManager.GetString("RepOutgoingSmsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string RepOverview {
            get {
                return ResourceManager.GetString("RepOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning customers.
        /// </summary>
        public static string RepReturningClientsChart {
            get {
                return ResourceManager.GetString("RepReturningClientsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string RepSecondsUnit {
            get {
                return ResourceManager.GetString("RepSecondsUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS/customer.
        /// </summary>
        public static string RepSmsPerClient {
            get {
                return ResourceManager.GetString("RepSmsPerClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS/day.
        /// </summary>
        public static string RepSmsPerDayUnit {
            get {
                return ResourceManager.GetString("RepSmsPerDayUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string RepSmsUnit {
            get {
                return ResourceManager.GetString("RepSmsUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string RepTags {
            get {
                return ResourceManager.GetString("RepTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags/conversation.
        /// </summary>
        public static string RepTagsPerConversationUnit {
            get {
                return ResourceManager.GetString("RepTagsPerConversationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of customers giving feedback.
        /// </summary>
        public static string RepTotalNoOfClients {
            get {
                return ResourceManager.GetString("RepTotalNoOfClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of clients.
        /// </summary>
        public static string RepTotalNoOfClientsTooltip {
            get {
                return ResourceManager.GetString("RepTotalNoOfClientsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of SMS.
        /// </summary>
        public static string RepTotalNoOfSms {
            get {
                return ResourceManager.GetString("RepTotalNoOfSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of SMS.
        /// </summary>
        public static string RepTotalNoOfSmsTooltip {
            get {
                return ResourceManager.GetString("RepTotalNoOfSmsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All SMS.
        /// </summary>
        public static string RepTotalSmsChart {
            get {
                return ResourceManager.GetString("RepTotalSmsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string RepTypeTable {
            get {
                return ResourceManager.GetString("RepTypeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string RepValueTable {
            get {
                return ResourceManager.GetString("RepValueTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string RepWeek {
            get {
                return ResourceManager.GetString("RepWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string sendButton {
            get {
                return ResourceManager.GetString("sendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string sendEmailCancel {
            get {
                return ResourceManager.GetString("sendEmailCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ] and [.
        /// </summary>
        public static string sendEmailConjuctionSubject {
            get {
                return ResourceManager.GetString("sendEmailConjuctionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent!.
        /// </summary>
        public static string sendEmailEmailSent {
            get {
                return ResourceManager.GetString("sendEmailEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfuly.
        /// </summary>
        public static string sendEmailEmailSentSuccessfuly {
            get {
                return ResourceManager.GetString("sendEmailEmailSentSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        public static string sendEmailHeader {
            get {
                return ResourceManager.GetString("sendEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string sendEmailLoadingScreen {
            get {
                return ResourceManager.GetString("sendEmailLoadingScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Message:.
        /// </summary>
        public static string sendEmailMessage {
            get {
                return ResourceManager.GetString("sendEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txt exchange between [.
        /// </summary>
        public static string sendEmailPrefixSubject {
            get {
                return ResourceManager.GetString("sendEmailPrefixSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string sendEmailSend {
            get {
                return ResourceManager.GetString("sendEmailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        public static string sendEmailSendingEmail {
            get {
                return ResourceManager.GetString("sendEmailSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from TxtFeedback user.
        /// </summary>
        public static string sendEmailStartingText {
            get {
                return ResourceManager.GetString("sendEmailStartingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Subject:.
        /// </summary>
        public static string sendEmailSubject {
            get {
                return ResourceManager.GetString("sendEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *To:.
        /// </summary>
        public static string sendEmailTo {
            get {
                return ResourceManager.GetString("sendEmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid. .
        /// </summary>
        public static string sendEmailValidationEmailInvalid {
            get {
                return ResourceManager.GetString("sendEmailValidationEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required. .
        /// </summary>
        public static string sendEmailValidationEmailRequired {
            get {
                return ResourceManager.GetString("sendEmailValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is required. .
        /// </summary>
        public static string sendEmailValidationMessageRequired {
            get {
                return ResourceManager.GetString("sendEmailValidationMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is required. .
        /// </summary>
        public static string sendEmailValidationSubjectRequired {
            get {
                return ResourceManager.GetString("sendEmailValidationSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback has been sent - the TxtFeedback team thanks you for your time!.
        /// </summary>
        public static string sendFeedbackFeedbackSentSuccessfully {
            get {
                return ResourceManager.GetString("sendFeedbackFeedbackSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string sendFeedbackHeader {
            get {
                return ResourceManager.GetString("sendFeedbackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t like the fact that....
        /// </summary>
        public static string sendFeedbackNegativeFeedbackSubject {
            get {
                return ResourceManager.GetString("sendFeedbackNegativeFeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace this with your input.
        /// </summary>
        public static string sendFeedbackPlaceholderMessage {
            get {
                return ResourceManager.GetString("sendFeedbackPlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like the fact that....
        /// </summary>
        public static string sendFeedbackPositiveFeedbackSubject {
            get {
                return ResourceManager.GetString("sendFeedbackPositiveFeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string settingsBtnChangePassword {
            get {
                return ResourceManager.GetString("settingsBtnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string settingsChangePassword {
            get {
                return ResourceManager.GetString("settingsChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string settingsChangePasswordTitle {
            get {
                return ResourceManager.GetString("settingsChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string settingsConfirmNewPasswordLabel {
            get {
                return ResourceManager.GetString("settingsConfirmNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string settingsCurrentPasswordLabel {
            get {
                return ResourceManager.GetString("settingsCurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords are required to be a minimum of {0} characters in length.
        /// </summary>
        public static string settingsDescriptionPrefix {
            get {
                return ResourceManager.GetString("settingsDescriptionPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string settingsErrorNewPasswordsDontMatch {
            get {
                return ResourceManager.GetString("settingsErrorNewPasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string settingsErrorPasswordChangeSummary {
            get {
                return ResourceManager.GetString("settingsErrorPasswordChangeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string settingsErrorPasswordIncorrect {
            get {
                return ResourceManager.GetString("settingsErrorPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must be at least {2} characters long..
        /// </summary>
        public static string settingsErrorPasswordNotLongEnough {
            get {
                return ResourceManager.GetString("settingsErrorPasswordNotLongEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string settingsNewPasswordLabel {
            get {
                return ResourceManager.GetString("settingsNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settingsPageTitle {
            get {
                return ResourceManager.GetString("settingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string settingsPasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("settingsPasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string settingsPrivacy {
            get {
                return ResourceManager.GetString("settingsPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User preferences.
        /// </summary>
        public static string settingUserPreferences {
            get {
                return ResourceManager.GetString("settingUserPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string starredLabel {
            get {
                return ResourceManager.GetString("starredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string supportLabel {
            get {
                return ResourceManager.GetString("supportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string tabHelp {
            get {
                return ResourceManager.GetString("tabHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversations.
        /// </summary>
        public static string tabMessages {
            get {
                return ResourceManager.GetString("tabMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string tabReports {
            get {
                return ResourceManager.GetString("tabReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag(s): .
        /// </summary>
        public static string tagsLabel {
            get {
                return ResourceManager.GetString("tagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last updated.
        /// </summary>
        public static string toDate {
            get {
                return ResourceManager.GetString("toDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn date filtering on/off.
        /// </summary>
        public static string tooltipIncludeDateInFilter {
            get {
                return ResourceManager.GetString("tooltipIncludeDateInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn favorites filtering on/off.
        /// </summary>
        public static string tooltipIncludeStarredInFilter {
            get {
                return ResourceManager.GetString("tooltipIncludeStarredInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick access to support conversations.
        /// </summary>
        public static string tooltipIncludeSupportFilter {
            get {
                return ResourceManager.GetString("tooltipIncludeSupportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn tag filtering on/off.
        /// </summary>
        public static string tooltipIncludeTagsInFilter {
            get {
                return ResourceManager.GetString("tooltipIncludeTagsInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn only unread conversations on/off.
        /// </summary>
        public static string tooltipIncludeUnreadInFilter {
            get {
                return ResourceManager.GetString("tooltipIncludeUnreadInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as favorite.
        /// </summary>
        public static string tooltipMarkAsFavouriteImg {
            get {
                return ResourceManager.GetString("tooltipMarkAsFavouriteImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of conversations with unread messages.
        /// </summary>
        public static string tooltipNrOfConvsWithUnreadMsgs {
            get {
                return ResourceManager.GetString("tooltipNrOfConvsWithUnreadMsgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send reply to customer.
        /// </summary>
        public static string tooltipReplyBtn {
            get {
                return ResourceManager.GetString("tooltipReplyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as email.
        /// </summary>
        public static string tooltipSendEmailImg {
            get {
                return ResourceManager.GetString("tooltipSendEmailImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send negative feedback.
        /// </summary>
        public static string tooltipSendNegativeFeedback {
            get {
                return ResourceManager.GetString("tooltipSendNegativeFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send positive feedback.
        /// </summary>
        public static string tooltipSendPositiveFeedback {
            get {
                return ResourceManager.GetString("tooltipSendPositiveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable displaying of messages for this working point.
        /// </summary>
        public static string tooltipWpImg {
            get {
                return ResourceManager.GetString("tooltipWpImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcomeMessage {
            get {
                return ResourceManager.GetString("welcomeMessage", resourceCulture);
            }
        }
    }
}
