//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmsFeedback_Take4.GlobalResources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string accountAuthenticate {
            get {
                return ResourceManager.GetString("accountAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string accountInformation {
            get {
                return ResourceManager.GetString("accountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a tag.
        /// </summary>
        public static string addATagLabel {
            get {
                return ResourceManager.GetString("addATagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string dateLabel {
            get {
                return ResourceManager.GetString("dateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string fromDate {
            get {
                return ResourceManager.GetString("fromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string loginUnsuccessfulDetails {
            get {
                return ResourceManager.GetString("loginUnsuccessfulDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string loginUnsuccessfulSummary {
            get {
                return ResourceManager.GetString("loginUnsuccessfulSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOnButtonMessage {
            get {
                return ResourceManager.GetString("LogOnButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string logOnLogOffMsg {
            get {
                return ResourceManager.GetString("logOnLogOffMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on.
        /// </summary>
        public static string logOnLogOnMsg {
            get {
                return ResourceManager.GetString("logOnLogOnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string logOnMessage {
            get {
                return ResourceManager.GetString("logOnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LogOnModel_Password_DisplayName {
            get {
                return ResourceManager.GetString("LogOnModel_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required.
        /// </summary>
        public static string LogOnModel_Password_Required {
            get {
                return ResourceManager.GetString("LogOnModel_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string LogOnModel_RememberMe_DisplayName {
            get {
                return ResourceManager.GetString("LogOnModel_RememberMe_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LogOnModel_UserName_DisplayName {
            get {
                return ResourceManager.GetString("LogOnModel_UserName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User name field is required.
        /// </summary>
        public static string LogOnModel_UserName_Required {
            get {
                return ResourceManager.GetString("LogOnModel_UserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string logOnRegister {
            get {
                return ResourceManager.GetString("logOnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have an account.
        /// </summary>
        public static string logOnRegisterSuffixMsg {
            get {
                return ResourceManager.GetString("logOnRegisterSuffixMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user name and password..
        /// </summary>
        public static string logOnWithUserPassMsg {
            get {
                return ResourceManager.GetString("logOnWithUserPassMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread.
        /// </summary>
        public static string readLabel {
            get {
                return ResourceManager.GetString("readLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string sendButton {
            get {
                return ResourceManager.GetString("sendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string starredLabel {
            get {
                return ResourceManager.GetString("starredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string tabHelp {
            get {
                return ResourceManager.GetString("tabHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string tabMessages {
            get {
                return ResourceManager.GetString("tabMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string tabReports {
            get {
                return ResourceManager.GetString("tabReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag(s): .
        /// </summary>
        public static string tagsLabel {
            get {
                return ResourceManager.GetString("tagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string toDate {
            get {
                return ResourceManager.GetString("toDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn date filtering on/off.
        /// </summary>
        public static string tooltipIncludeDateInFilter {
            get {
                return ResourceManager.GetString("tooltipIncludeDateInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn favorites filtering on/off.
        /// </summary>
        public static string tooltipIncludeStarredInFilter {
            get {
                return ResourceManager.GetString("tooltipIncludeStarredInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn tag filtering on/off.
        /// </summary>
        public static string tooltipIncludeTagsInFilter {
            get {
                return ResourceManager.GetString("tooltipIncludeTagsInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn only unread conversations on/off.
        /// </summary>
        public static string tooltipIncludeUnreadInFilter {
            get {
                return ResourceManager.GetString("tooltipIncludeUnreadInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as favorite.
        /// </summary>
        public static string tooltipMarkAsFavouriteImg {
            get {
                return ResourceManager.GetString("tooltipMarkAsFavouriteImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send reply to customer.
        /// </summary>
        public static string tooltipReplyBtn {
            get {
                return ResourceManager.GetString("tooltipReplyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as email.
        /// </summary>
        public static string tooltipSendEmailImg {
            get {
                return ResourceManager.GetString("tooltipSendEmailImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable displaying of messages for this working point.
        /// </summary>
        public static string tooltipWpImg {
            get {
                return ResourceManager.GetString("tooltipWpImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcomeMessage {
            get {
                return ResourceManager.GetString("welcomeMessage", resourceCulture);
            }
        }
    }
}
