//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFeedback_EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.SubscriptionDetails = new HashSet<SubscriptionDetail>();
            this.SubscriptionDetails1 = new HashSet<SubscriptionDetail>();
            this.Companies = new HashSet<Company>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Landline { get; set; }
    
        public virtual ICollection<SubscriptionDetail> SubscriptionDetails { get; set; }
        public virtual ICollection<SubscriptionDetail> SubscriptionDetails1 { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
    }
}
