//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFeedback_EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversationHistory
    {
        public int Id { get; set; }
        public int Sequence { get; set; }
        public System.DateTime Date { get; set; }
        public string EventTypeName { get; set; }
        public string ConversationConvId { get; set; }
        public int MessageId { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual Conversation Conversation { get; set; }
        public virtual Message Message { get; set; }
    }
}
