//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFeedback_EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventType
    {
        public EventType()
        {
            this.ConversationHistoryEvents = new HashSet<ConversationHistory>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public string FriendlyName { get; set; }
    
        public virtual ICollection<ConversationHistory> ConversationHistoryEvents { get; set; }
    }
}
