//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFeedback_EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetailsTemplate
    {
        public InvoiceDetailsTemplate()
        {
            this.SubscriptionDetails = new HashSet<SubscriptionDetail>();
            this.SubscriptionDetails1 = new HashSet<SubscriptionDetail>();
        }
    
        public int InvoiceDetailsTemplateID { get; set; }
        public string Article { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal VAT { get; set; }
    
        public virtual ICollection<SubscriptionDetail> SubscriptionDetails { get; set; }
        public virtual ICollection<SubscriptionDetail> SubscriptionDetails1 { get; set; }
    }
}
