//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFeedback_EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.AutoGenerated = false;
            this.InvoiceDetails = new HashSet<InvoiceDetails>();
        }
    
        public int InvoiceId { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public string ProposalDetails { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<decimal> AdvancePaymentTax { get; set; }
        public bool Paid { get; set; }
        public string CompanyName { get; set; }
        public int InvoiceNumber { get; set; }
        public string Currency { get; set; }
        public bool AutoGenerated { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<InvoiceDetails> InvoiceDetails { get; set; }
    }
}
