//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFeedback_EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.IsSmsBased = false;
            this.ConversationHistories = new HashSet<ConversationHistory>();
        }
    
        public int Id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Text { get; set; }
        public System.DateTime TimeReceived { get; set; }
        public bool Read { get; set; }
        public string ConversationId { get; set; }
        public Nullable<long> ResponseTime { get; set; }
        public bool IsSmsBased { get; set; }
        public string XmppConnectionXmppUser { get; set; }
        public string ExternalID { get; set; }
        public string Price { get; set; }
        public bool ClientAcknowledge { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual ICollection<ConversationHistory> ConversationHistories { get; set; }
        public virtual XmppConnection XmppConnection { get; set; }
    }
}
