//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFeedback_EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smsfeedbackEntities : DbContext
    {
        public smsfeedbackEntities()
            : base("name=smsfeedbackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Conversation> Conversations { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<WorkingPoint> WorkingPoints { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<XmppConnection> XmppConnections { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<Membership> Memberships { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<ConversationTag> ConversationTags { get; set; }
        public DbSet<ActivityLogWorkingPoint> ActivityLogWorkingPoints { get; set; }
        public DbSet<TagType> TagTypes { get; set; }
        public DbSet<TagTagType> TagTagTypes { get; set; }
        public DbSet<EventType> EventTypes { get; set; }
        public DbSet<ConversationHistory> ConversationHistories { get; set; }
        public DbSet<InvoiceDetails> InvoiceDetails { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<SubscriptionDetail> SubscriptionDetails { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<InvoiceDetailsTemplate> InvoiceDetailsTemplates { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<Device> Devices { get; set; }
    }
}
