//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFeedback_EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.ConversationTags = new HashSet<ConversationTag>();
            this.TagTagTypes = new HashSet<TagTagType>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public string CompanyName { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<ConversationTag> ConversationTags { get; set; }
        public virtual ICollection<TagTagType> TagTagTypes { get; set; }
    }
}
