//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFeedback_EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagType
    {
        public TagType()
        {
            this.TagTagTypes = new HashSet<TagTagType>();
        }
    
        public string Type { get; set; }
    
        public virtual ICollection<TagTagType> TagTagTypes { get; set; }
    }
}
