//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFeedback_EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagTagType
    {
        public bool IsDefault { get; set; }
        public string TagName { get; set; }
        public string TagCompanyName { get; set; }
        public string TagTypeType { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual TagType TagType { get; set; }
    }
}
