//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFeedback_EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingPoint
    {
        public WorkingPoint()
        {
            this.BusyMessageTimer = 5000;
            this.Users = new HashSet<User>();
            this.Conversations = new HashSet<Conversation>();
            this.ActivityLogWorkingPoints = new HashSet<ActivityLogWorkingPoint>();
        }
    
        public string TelNumber { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string Provider { get; set; }
        public int SentSms { get; set; }
        public int MaxNrOfSmsToSend { get; set; }
        public string SupportConversation { get; set; }
        public string ShortID { get; set; }
        public string WelcomeMessage { get; set; }
        public string XMPPsuffix { get; set; }
        public string BusyMessage { get; set; }
        public string OutsideOfficeHoursMessage { get; set; }
        public string Language { get; set; }
        public int BusyMessageTimer { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Conversation> Conversations { get; set; }
        public virtual ICollection<ActivityLogWorkingPoint> ActivityLogWorkingPoints { get; set; }
        public virtual Conversation ConversationForSupport { get; set; }
    }
}
